# Generated by Django 3.2.9 on 2021-11-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('barrio', models.CharField(max_length=100, verbose_name='Barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietarios.propietario')),
            ],
            options={
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Viviendas',
            },
        ),
    ]
